from datetime import UTC, datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from sqlalchemy import select
from sqlalchemy.orm import Session as DbSession

from app.core.config import settings
from app.models.assessment import Assessment
from app.models.ergonomic_event import ErgonomicEvent
from app.models.report import Report
from app.models.session import Session
from app.models.session_worker import SessionWorker
from app.models.snapshot import Snapshot
from app.models.user import User
from app.models.worker import Worker


def generate_session_pdf_report(
    db: DbSession,
    session: Session,
    current_user: User,
) -> Report:
    now = datetime.now(UTC)
    report_dir = settings.media_root / "reports" / current_user.id / session.id
    report_dir.mkdir(parents=True, exist_ok=True)
    output_path = report_dir / f"{session.session_code}_ergonomic_report.pdf"

    worker_rows = db.execute(
        select(SessionWorker, Worker)
        .outerjoin(Worker, SessionWorker.worker_id == Worker.id)
        .where(SessionWorker.session_id == session.id)
        .order_by(SessionWorker.created_at)
    ).all()
    events = list(
        db.scalars(
            select(ErgonomicEvent)
            .where(ErgonomicEvent.session_id == session.id)
            .order_by(ErgonomicEvent.started_at.desc())
        )
    )
    assessments = list(
        db.scalars(
            select(Assessment)
            .where(Assessment.session_id == session.id)
            .order_by(Assessment.calculated_at.desc())
        )
    )
    snapshots_by_event = _snapshots_by_event(db, session.id)

    _write_pdf(output_path, session, current_user, worker_rows, events, assessments, snapshots_by_event)

    report = Report(
        owner_user_id=current_user.id,
        session_id=session.id,
        report_type="session_pdf",
        status="ready",
        file_path=str(output_path),
        generated_by=current_user.email,
        generated_at=now,
        metadata_json={
            "session_code": session.session_code,
            "event_count": len(events),
            "worker_count": len(worker_rows),
            "reviewed_assessment_count": sum(
                assessment.assessment_status == "reviewed" for assessment in assessments
            ),
        },
    )
    db.add(report)
    db.commit()
    db.refresh(report)
    return report


def _write_pdf(
    output_path: Path,
    session: Session,
    current_user: User,
    worker_rows: list[tuple[SessionWorker, Worker | None]],
    events: list[ErgonomicEvent],
    assessments: list[Assessment],
    snapshots_by_event: dict[str, list[Snapshot]],
) -> None:
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ErgoTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        spaceAfter=8,
    )
    heading_style = ParagraphStyle(
        "ErgoHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        spaceBefore=14,
        spaceAfter=8,
    )
    body_style = ParagraphStyle("ErgoBody", parent=styles["BodyText"], fontSize=9, leading=12)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        rightMargin=14 * mm,
        leftMargin=14 * mm,
        topMargin=14 * mm,
        bottomMargin=14 * mm,
        title=f"{session.session_code} Ergonomic Report",
    )
    story = [
        Paragraph("Ergonomic Session Report", title_style),
        Paragraph(f"Generated by {current_user.email} on {_format_dt(datetime.now(UTC))}", body_style),
        Spacer(1, 6),
    ]

    story.append(Paragraph("Session Summary", heading_style))
    story.append(
        _table(
            [
                ["Session", session.session_code],
                ["Status", session.status],
                ["Notes", session.notes or "-"],
                ["Started", _format_dt(session.started_at)],
                ["Stopped", _format_dt(session.stopped_at)],
                ["Completed", _format_dt(session.completed_at)],
            ],
            col_widths=[36 * mm, 132 * mm],
        )
    )

    story.append(Paragraph("Workers", heading_style))
    story.append(_worker_table(worker_rows))

    story.append(Paragraph("Reviewed Assessments", heading_style))
    story.append(_assessment_table(assessments))

    story.append(Paragraph("Risk Event Timeline", heading_style))
    risk_events = [
        event
        for event in events
        if event.event_type in {"high_risk_posture", "sustained_high_risk"}
    ][:12]
    if not risk_events:
        story.append(Paragraph("No high-risk events recorded for this session.", body_style))
    for event in risk_events:
        story.extend(_event_block(event, worker_rows, assessments, snapshots_by_event, body_style))

    doc.build(story)


def _worker_table(worker_rows: list[tuple[SessionWorker, Worker | None]]) -> Table | Paragraph:
    if not worker_rows:
        return Paragraph("No workers were observed.", getSampleStyleSheet()["BodyText"])
    data = [["Worker", "Employee No.", "Edge ID", "Identity"]]
    for session_worker, worker in worker_rows:
        data.append(
            [
                worker.name if worker else session_worker.edge_worker_id,
                worker.employee_number if worker and worker.employee_number else "-",
                session_worker.edge_worker_id,
                session_worker.identity_status,
            ]
        )
    return _table(data, col_widths=[56 * mm, 34 * mm, 38 * mm, 36 * mm], header=True)


def _assessment_table(assessments: list[Assessment]) -> Table | Paragraph:
    reviewed = [row for row in assessments if row.assessment_status == "reviewed"]
    if not reviewed:
        return Paragraph("No reviewed assessments yet.", getSampleStyleSheet()["BodyText"])
    data = [["Type", "Final Score", "Risk", "Load", "Activity", "Coupling/Wrist", "Reviewed At"]]
    for assessment in reviewed[:20]:
        manual = assessment.breakdown.get("manual_inputs", {})
        data.append(
            [
                assessment.assessment_type.upper(),
                str(assessment.score),
                assessment.risk_level,
                str(manual.get("load_score", "-")),
                str(manual.get("activity_score", "-")),
                str(manual.get("coupling_score", manual.get("wrist_twist_score", "-"))),
                _format_dt(assessment.calculated_at),
            ]
        )
    return _table(data, col_widths=[18 * mm, 22 * mm, 30 * mm, 18 * mm, 22 * mm, 30 * mm, 32 * mm], header=True)


def _event_block(
    event: ErgonomicEvent,
    worker_rows: list[tuple[SessionWorker, Worker | None]],
    assessments: list[Assessment],
    snapshots_by_event: dict[str, list[Snapshot]],
    body_style: ParagraphStyle,
) -> list:
    worker_name = _worker_name(event.session_worker_id, worker_rows)
    related_reviews = [
        assessment
        for assessment in assessments
        if assessment.ergonomic_event_id == event.id and assessment.assessment_status == "reviewed"
    ]
    review_text = ", ".join(
        f"{row.assessment_type.upper()} {row.score} ({row.risk_level})" for row in related_reviews
    ) or "not reviewed"
    rows = [
        ["Worker", worker_name],
        ["Event", _event_label(event.event_type)],
        ["Severity", event.severity],
        ["Score", f"{(event.score_type or '-').upper()} {event.score or '-'}"],
        ["Started", _format_dt(event.started_at)],
        ["Duration", _duration(event.duration_ms)],
        ["Review", review_text],
    ]
    block: list = [_table(rows, col_widths=[30 * mm, 78 * mm])]
    snapshot = next(
        (row for row in snapshots_by_event.get(event.id, []) if Path(row.file_path).is_file()),
        None,
    )
    if snapshot is not None:
        try:
            block.append(Spacer(1, 4))
            block.append(Image(snapshot.file_path, width=108 * mm, height=60 * mm, kind="proportional"))
        except OSError:
            block.append(Paragraph("Snapshot file could not be loaded.", body_style))
    block.append(Spacer(1, 8))
    return [KeepTogether(block)]


def _table(data: list[list[str]], col_widths: list[float], header: bool = False) -> Table:
    table = Table(data, colWidths=col_widths, hAlign="LEFT")
    style = [
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d8dedf")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("LEADING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    if header:
        style.extend(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#176d6a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    else:
        style.extend(
            [
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#edf3f2")),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ]
        )
    table.setStyle(TableStyle(style))
    return table


def _snapshots_by_event(db: DbSession, session_id: str) -> dict[str, list[Snapshot]]:
    snapshots = db.scalars(
        select(Snapshot)
        .where(Snapshot.session_id == session_id, Snapshot.ergonomic_event_id.is_not(None))
        .order_by(Snapshot.captured_at.desc())
    )
    result: dict[str, list[Snapshot]] = {}
    for snapshot in snapshots:
        if snapshot.ergonomic_event_id:
            result.setdefault(snapshot.ergonomic_event_id, []).append(snapshot)
    return result


def _worker_name(
    session_worker_id: str,
    worker_rows: list[tuple[SessionWorker, Worker | None]],
) -> str:
    for session_worker, worker in worker_rows:
        if session_worker.id == session_worker_id:
            return worker.name if worker else session_worker.edge_worker_id
    return "Unknown worker"


def _event_label(value: str) -> str:
    labels = {
        "high_risk_posture": "High Risk Posture",
        "sustained_high_risk": "Sustained High Risk",
        "worker_observed": "Worker Observed",
        "worker_entered": "Worker Entered",
        "worker_left": "Worker Left",
    }
    return labels.get(value, value.replace("_", " ").title())


def _format_dt(value: datetime | None) -> str:
    if value is None:
        return "-"
    return value.astimezone(UTC).strftime("%Y-%m-%d %H:%M UTC")


def _duration(value: int | None) -> str:
    if not value:
        return "0s"
    seconds = max(0, round(value / 1000))
    minutes, remaining = divmod(seconds, 60)
    if minutes:
        return f"{minutes}m {remaining}s"
    return f"{remaining}s"
